push

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -270,7 +270,27 @@ jobs:
             fi
       - destroy-environment
       - revert-migrations
-      # Here's where you will add some code to rollback on failure      
+      # Here's where you will add some code to rollback on failure
+  smoke-test-frontend:
+    docker:
+      - image: sleavely/node-awscli:14.x
+    steps:
+      - checkout 
+      
+      - run:
+          name: Frontend smoke test.
+          command: |
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+            echo ${URL} 
+            if curl -s  --head ${URL} 
+            then
+              exit 1
+            else
+              exit 1
+            fi
+      - destroy-environment
+      - revert-migrations
+           
   deploy-backend:
 
     docker:
@@ -374,7 +394,7 @@ workflows:
       - scan-backend:
           requires: [build-backend]
       - deploy-infrastructure
-      
+
       - configure-infrastructure:
           requires: [deploy-infrastructure]
       - run-migrations:
